In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [26]:
df_train = pd.read_csv("D:\\Skills\\ACM Sigchi\\Week 1\\Bonus\\house-prices-advanced-regression-techniques\\train.csv")
df_test = pd.read_csv("D:\\Skills\\ACM Sigchi\\Week 1\\Bonus\\house-prices-advanced-regression-techniques\\test.csv")

df = pd.concat([df_train, df_test], axis=0)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [27]:
X = df.iloc[:, :-1]
y_train = df_train.iloc[:, -1]

In [28]:
columnsTodrop = ['PoolQC', 'MiscFeature', 'Alley', 'Fence']
X.drop(columns=columnsTodrop, inplace=True)

In [29]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')
X_imputed = imputer.fit_transform(X)

In [31]:
X_imputed = pd.DataFrame(X_imputed, columns=X.columns)

In [33]:
for column in X_imputed.select_dtypes(include=['object']).columns:
    try:
        X_imputed[column] = pd.to_numeric(X_imputed[column])
    except ValueError:
        pass

In [34]:
X_imputed.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,61,0,0,0,0,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,42,0,0,0,0,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,35,272,0,0,0,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,84,0,0,0,0,0,12,2008,WD,Normal

In [37]:
X_numerical = X_imputed.select_dtypes(include=['int64', 'float64'])
X_categorical = X_imputed.select_dtypes(object)

In [38]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for column in X_categorical.columns:
    X_categorical[column] = encoder.fit_transform(X_categorical[column])

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_numerical_scaled = scaler.fit_transform(X_numerical)

In [41]:
X_numerical_scaled = pd.DataFrame(df_numerical_scaled, columns=X_numerical.columns)

In [42]:
X_numerical_scaled.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,-1.731458,0.067331,-0.127678,-0.217879,0.646183,-0.507284,1.046258,0.896833,0.529034,0.581145,...,0.349364,-0.740760,0.200006,-0.359601,-0.103331,-0.285935,-0.06315,-0.089592,-1.552184,0.157646
1,-1.730271,-0.873616,0.567125,-0.072044,-0.063185,2.188279,0.154764,-0.395604,-0.567016,1.178255,...,-0.058991,1.614879,-0.702843,-0.359601,-0.103331,-0.285935,-0.06315,-0.089592,-0.446925,-0.602962
2,-1.729084,0.067331,0.011283,0.137197,0.646183,-0.507284,0.980221,0.848965,0.338903,0.098189,...,0.627787,-0.740760,-0.081209,-0.359601,-0.103331,-0.285935,-0.06315,-0.089592,1.026753,0.157646
3,-1.727897,0.302568,-0.359279,-0.078385,0.646183,-0.507284,-1.859351,-0.682812,-0.567016,-0.494529,...,0.785561,-0.740760,-0.184815,3.874967,-0.103331,-0.285935,-0.06315,-0.089592,-1.552184,-1.363569
4,-1.726711,0.067331,0.752406,0.518903,1.355551,-0.507284,0.947203,0.753229,1.390216,0.469187,...,1.685798,0.776967,0.540424,-0.359601,-0.103331,-0.285935,-0.06315,-0.089592,2.132012,0.157646

In [45]:
X_processed = pd.concat([X_numerical_scaled, X_categorical], axis=1)
X_processed.drop(columns=['Id'], inplace=True)

In [52]:
X_train = np.array(X_processed[0:df_train.shape[0]])
X_test = np.array(X_processed[df_train.shape[0]:])

In [55]:
y_train = np.array(y_train)

In [56]:
from sklearn.model_selection import train_test_split

X_to_train, X_valid, y_to_train, y_valid = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [58]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_to_train, y_to_train)

y_pred = model.predict(X_valid)

In [60]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100)
model.fit(X_to_train, y_to_train)

y_pred = model.predict(X_valid)

In [61]:
from sklearn.metrics import r2_score

print(f"R2 Score = {r2_score(y_true=y_valid, y_pred=y_pred)}")

R2 Score = 0.89332680054847

In [64]:
from sklearn.svm import SVR

model = SVR(kernel='poly')
model.fit(X_to_train, y_to_train)

y_pred = model.predict(X_valid)

In [65]:
from sklearn.metrics import r2_score

print(f"R2 Score = {r2_score(y_true=y_valid, y_pred=y_pred)}")

R2 Score = -0.02343566551573062

In [76]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

param_grids = {
    'Linear Regression': {},
    'Random Forest Regressor': {
        'n_estimators': [50, 100, 200]
    },
    'Support Vector Regressor': {
        'kernel': ['linear', 'rbf']
    },
    'Gradient Boosting Regressor': {
        'n_estimators': [100, 200]
    },
    'XGBoost Regressor': {
        'n_estimators': [100, 200]
    }
}

models = {
    'Linear Regression': LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(),
    'Support Vector Regressor': SVR(),
    'Gradient Boosting Regressor': GradientBoostingRegressor(),
    'XGBoost Regressor': XGBRegressor(eval_metric='mlogloss')
}
for model_name, model in models.items():
    param_grid = param_grids[model_name]
    
    if not param_grid:
        model.fit(X_to_train, y_to_train)
        y_pred = model.predict(X_valid)
        r2 = r2_score(y_valid, y_pred)
        print(f"{model_name} - R2 Score on Test Data: {r2:.4f}")
        continue

    grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')
    grid_search.fit(X_to_train, y_to_train)
    
    print(f"{model_name} - Best Parameters: {grid_search.best_params_}")
    print(f"{model_name} - Best Score: {-grid_search.best_score_:.4f}")
    
    best_model = grid_search.best_estimator_
    y_pred = best_model.predict(X_valid)
    r2 = r2_score(y_valid, y_pred)
    print(f"{model_name} - R2 score on Test Data: {r2:.4f}")

Linear Regression - R2 Score on Test Data: 0.8481
Random Forest Regressor - Best Parameters: {'n_estimators': 200}
Random Forest Regressor - Best Score: 934735869.8567
Random Forest Regressor - R2 score on Test Data: 0.8919
Support Vector Regressor - Best Parameters: {'kernel': 'linear'}
Support Vector Regressor - Best Score: 5274737777.2405
Support Vector Regressor - R2 score on Test Data: 0.1602
Gradient Boosting Regressor - Best Parameters: {'n_estimators': 200}
Gradient Boosting Regressor - Best Score: 872545728.3372
Gradient Boosting Regressor - R2 score on Test Data: 0.9032
XGBoost Regressor - Best Parameters: {'n_estimators': 200}
XGBoost Regressor - Best Score: 967863353.8732
XGBoost Regressor - R2 score on Test Data: 0.9134

**PRODUCING FINAL TEST RESULTS**

In [77]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=200)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [82]:
test_ids = np.arange(1461, 2920)

submission_dict = {
                  'Id': test_ids,
                  'SalePrice': y_pred
                 }

submission = pd.DataFrame(submission_dict)

In [83]:
submission.head()

     Id      SalePrice
0  1461  115549.437500
1  1462  157241.093750
2  1463  186896.265625
3  1464  194896.562500
4  1465  188213.781250

In [84]:
submission.to_csv("D:\\Skills\\ACM Sigchi\\Week 1\\Bonus\\submission.csv", index=False)